#!/usr/bin/env python3
"""Regenerate data/tracks.js from the original 2015 dataset.

    python3 tools/build-tracks.py

Reads legacy/data/data.json and writes data/tracks.js, which the page loads
with a plain <script> tag rather than fetch(), so the site also works when
opened straight off disk.

What it normalises:
  - duplicate source+id pairs are dropped (1,318 rows in, 1,257 out)
  - YouTube ISO-8601 durations ("PT6M31S") become seconds
  - SoundCloud millisecond durations become seconds
  - keys are shortened, since this file ships to every visitor
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "legacy", "data", "data.json")
DEST = os.path.join(ROOT, "data", "tracks.js")

ISO = re.compile(r"^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?$")


def yt_seconds(value):
    m = ISO.match(value or "")
    if not m:
        return 0
    h, mi, se = m.groups()
    return int(h or 0) * 3600 + int(mi or 0) * 60 + int(float(se or 0))


def main():
    with open(SRC) as f:
        source = json.load(f)

    out, seen, dupes, bad = [], set(), 0, 0
    for t in source:
        tid = (t.get("id") or "").strip()
        origin = t.get("source")
        if not tid or origin not in ("YT", "SC"):
            bad += 1
            continue

        key = origin + ":" + tid
        if key in seen:
            dupes += 1
            continue
        seen.add(key)

        if origin == "YT":
            duration = yt_seconds(t.get("duration"))
        else:
            try:
                duration = int(round(float(t.get("duration") or 0) / 1000))
            except (TypeError, ValueError):
                duration = 0

        out.append({
            "k": key,
            "s": origin,
            "i": tid,
            "t": (t.get("title") or "Untitled").strip(),
            "v": (t.get("author") or "").strip(),   # who posted it
            "d": duration,
            "a": t.get("thumbnail") or "",
            "c": (t.get("created_time") or "")[:10],
        })

    os.makedirs(os.path.dirname(DEST), exist_ok=True)
    with open(DEST, "w") as f:
        f.write("// Generated by tools/build-tracks.py — do not edit by hand.\n")
        f.write("window.MASH_TRACKS = ")
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print("wrote %s" % os.path.relpath(DEST, ROOT))
    print("  %d tracks (%d duplicates dropped, %d unusable)" % (len(out), dupes, bad))
    print("  %d YouTube, %d SoundCloud" % (
        sum(1 for t in out if t["s"] == "YT"),
        sum(1 for t in out if t["s"] == "SC"),
    ))


if __name__ == "__main__":
    sys.exit(main())
